### ISSUE TITLE
Update cisa/pe-reports with latest working version.

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#12]
# 💡 Summary #

Update the cisa/pe-reports repo with current/active scripts used by the P&E Team to run P&E Reports. 

## Motivation and context ##

Currently the P&E Team has working scripts that produce the bi-weekly P&E Cyber Hygiene Reports. The code improvement provides full report output which is to merge into the dev-standards architecture addressed in  https://github.com/cisagov/pe-reports/pull/6.  Introduction of Matplotlib graphing tools have been added for better visualizations.

Secondary end-to-end process improvements:
- https://github.com/cisagov/pe-reports/issues/7#issue-916345703
- https://github.com/cisagov/pe-reports/issues/9#issue-928601648

## Implementation notes ##

- Branch from - https://github.com/cisagov/pe-reports/pull/6.
- "Draft" PR "(initials)-wip-pe-reports-v1".
- Update code to cisa dev-standards = https://github.com/cisagov/skeleton-python-library.
- Merge to develop.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Report runs end-to-end from command-line.
- [ ] csv data embeds in deliverable PDFs.
- [ ] All linked issues are addressed.
- [ ] Final PDFs are encrypted.
- [ ] Code meets cisa dev-sandards and tests.
- [ ] Archive 'Version'.

**Comment by schmelz21** [comment]
Linked Dependancies:
- https://github.com/cisagov/pe-reports/issues/14
- https://github.com/cisagov/pe-reports/issues/13
- https://github.com/cisagov/pe-reports/issues/9
- https://github.com/cisagov/pe-reports/issues/8
- https://github.com/cisagov/pe-reports/issues/7

**Comment by schmelz21** [comment]
@aloftus23 , @cisagov/posture-and-exposure;
We were able to successfully merge https://github.com/cisagov/pe-reports/pull/6 to ensure we have the proper [dev-guidlines](https://github.com/cisagov/skeleton-python-library) applied to this repo. The [AL-working-v1.0](https://github.com/cisagov/pe-reports/tree/AL-working-v1.0) branch has working code with these dev-guidlines integrated, but fails pre-commits due to the following issues:

1. https://github.com/cisagov/pe-reports/issues/24
2. https://github.com/cisagov/pe-reports/issues/23

These 2 Issues **MUST** be addressed to be able to conduct commits and pull requests for this version. The code however can be cloned and ran locally with these actions:

1. Update the organizational list - [pe-reports/src/pe_reports/data/org_names.json](https://github.com/cisagov/pe-reports/blob/AL-working-v1.0/src/pe_reports/data/org_names.json) 
         >See @aloftus23 or @schmelz-ctr for list.

2. Use the proper cmd line arguments - https://github.com/cisagov/pe-reports/issues/8
