### ISSUE TITLE
Research usage of Docker to support P&E Report architecture.

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#42]
# 💡 Summary #

The primary goal is to build a transferable environment to run P&E Reports. The intended architecture includes a Python framework, Docker image and a Postgres database.

## Motivation and context ##

P&E Reports requires the process of scanning external resources for data, storing the data, export data/analytics to a formalized report and then deliver output via email to subscribed customers. A primary requirement is to create an environment that can be delivered by various 'users'. A contained solution would provide for this along with enhancing security and stability to all data processes.

Noted Resources:
- [Postgres Docker Image](https://hub.docker.com/_/postgres/)
- [Dockerizing Flask with Postgres, Gunicorn, and Nginx](https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/)
- [Async in Flask 2.0](https://testdriven.io/blog/flask-async/)
- [MS Sample Code](https://github.com/microsoft/python-sample-vscode-flask-tutorial)

## Implementation notes ##

- Discover and document probably solutions.
- Build a Proof-of-Concept (POC).

## Acceptance criteria ##

How do we know when this work is done?

- [x] Build Working POC
- [x] Validate solution meets [cisagov development standards](https://github.com/cisagov/development-guide).
- [x] Create implementation plan and sprint.

**Comment by stewartl97** [comment]
POC developed.  Submitted to @cduhn17 for further refinements before completion.

**Comment by schmelz21** [comment]
@stewartl97 and @cduhn17, I am closing this issue as we have created [pe-reports-docker](https://github.com/cisagov/pe-reports-docker) using dev-standard guidelines/skeleton and have created an implementation plan in [Sprint 7](https://github.com/cisagov/pe-reports/projects/7).
