### ISSUE TITLE
IP/DNS Validation - DNS Record Tracking, Validation and Sharing

### ISSUE THREAD

**Issue by edujosemena** [cisagov/pe-reports#529]
# 💡 Summary #

DNS records arent being tracked locally on our database. We want to be able to get dns information on current all current domains we have on our database aswell as other information and fill it in the dns_records table

## Motivation and context ##

Keeping track of this info on our database will be useful for when other teams ask us for information.

## Implementation notes ##

- Pull full FCEB DNS Details from DNS provider
- Data should be added to dns_info table for tracking purposes
- 
## Acceptance criteria ##

How do we know when this work is done?

- [ ] DNS records table contains pertinent information concerning record types, contacts, ip's, etc
- [ ] Data is accessible via API and web form
- [ ] Searches can be done using single or multiple domains
