### ISSUE TITLE
Add interface to manage application services.

### ISSUE THREAD

**Issue by schmelz21** [cisagov/pe-reports#93]
# 💡 Summary #

Posture and Exposure is looking to build an interface to manage the various processes for generating reports. A sensible solution would introduce the python `flask` package and supporting framework. Scope for the initial build is to run a browser locally and have UI tools to "add / edit / remove" customer account information.

Considerations in proposal:
- [pe-source](https://github.com/cisagov/pe-reports/issues/74) module implementation.
- [cisagov/pe-reports-docker](https://github.com/cisagov/pe-reports-docker) implementation.
- Work to be preformed in [Sprint. 7.](https://github.com/cisagov/pe-reports/projects/7)

## Motivation and context ##
- Provides an architecture to scale up additional customers and services.

## Implementation notes ##

Proposed architecture:
```
cisa/pe-reports-docker
├── src
│   ├── PIPEFILE -----> cisa/pe-reports
└── tests

cisa/pe-reports
├── app.py (flask)
├── config.py (Gunicorn, Ngix)
├── src
│   ├── __init__.py
│   ├── __main__.py
│   ├── views.py
│   ├── pe_reports
│   │   ├── data
│   │   └── report_generator.py
│   ├── pe_mailer
│   │   ├── data
│   │   └── mailer.py
│   ├── pe_source
│   │   ├── data
│   │   ├── api_source_1.py
│   ├── static
│   │   ├── index.html
└── tests
```

## Acceptance criteria ##

- [ ] Plan accepted by P&E
- [ ] Meets CISA development standards
- [ ] Issues created for build

**Comment by schmelz21** [comment]
@stewartl97 and @cduhn17 please review, and provide any additional feedback.
